"""Add groups and photo privacy features

Revision ID: e2043fbdee63
Revises: 
Create Date: 2025-12-05 03:12:48.495229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2043fbdee63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('gcs_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=False))
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               nullable=False)
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               nullable=True)
        batch_op.drop_column('visibility')
        batch_op.drop_column('gcs_path')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
